### ISSUE TITLE
What does pdu_dispatch in llcp_pdu do?

### ISSUE THREAD

**Issue by asheeshr** [JiapengLi/libllcp#1]
The implementation seems to have only error checking in it whereas the name suggests <i>transfer</i> (dispatch) of some sort. Hence, my question.

What exactly does the function do? Where is it supposed to be used?

**Comment by JiapengLi** [comment]
pdu_dispatch is used to divide multiple pdus in AGF frame into some standalnoe pdus, each of these pdus will be sent to llc_service_llc, and it will be analysed again.

By the way, the commits of this repo has been already publised on official libllcp repo. And a new socket branch is available, both win32 and linux is supported. It is appreciated if you could help to test it.

I think the socket branch now is more stable than the master branch.

https://code.google.com/p/libllcp/source/list?name=socket

**Comment by asheeshr** [comment]
Ahh! That makes sense. However, how does dividing a PDU relate to the word <i>dispatch</i>? I cant figure that one out.

I will be starting work on NFC using libllcp on Linux as soon as my NFC readers get delivered. I will provide feedback whenever I can.

**Comment by JiapengLi** [comment]
I think the author of this function just ignore the divide action, the purpose of dividing is dispatching indeed.
